export const SANS = "Helvetica Neue,Helvetica,Arial,sans-serif";

export function getTheme(dark) {
  return dark ? {
    utilBg: "#000",
    utilText: "#888",
    headerBg: "#111",
    headerBorder: "#222",
    navBorder: "#222",
    bg: "#000",
    surface: "#0a0a0a",
    surfaceHover: "#111",
    border: "#1e1e1e",
    borderLight: "#2a2a2a",
    text: "#fff",
    textMid: "#ccc",
    textMuted: "#666",
    textFaint: "#444",
    accent: "#fff",
    accentBg: "#ffffff12",
    inputBg: "#0a0a0a",
    noteBg: "#0a0a0a",
    footerBg: "#000",
  } : {
    utilBg: "#111",
    utilText: "#bbb",
    headerBg: "#111",
    headerBorder: "#222",
    navBorder: "#ddd",
    bg: "#fff",
    surface: "#fff",
    surfaceHover: "#f7f7f7",
    border: "#e8e8e8",
    borderLight: "#f0f0f0",
    text: "#111",
    textMid: "#444",
    textMuted: "#777",
    textFaint: "#aaa",
    accent: "#111",
    accentBg: "#11111110",
    inputBg: "#fff",
    noteBg: "#f5f5f5",
    footerBg: "#f5f5f5",
  };
}
